### ISSUE TITLE
Problem loading world

### ISSUE THREAD

**Issue by Usaywook** [Daffan/ros_jackal#7]
Because the singularity image is not pulled from https://github.com/Daffan/ros_jackal/issues/5#issue-1762255090, 

I changed "config/e2e_default_TD3.yaml" file to this
```
env_config:
  use_container: False
  world_name: "BARN/world_450.world"
  gui: True
```

It creates walls but no stationary or moving boxes or walls.

How can I run the benchmark environment without Singularity container?
